spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/security
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update